Calndar master
kostiantyn-chechel/clockware pull request #11
Opened 2021-03-24 08:10 UTC by kostiantyn-chechel

2021-03-25 09:26 UTC, darinasmile requested changes

2021-03-25 09:26 UTC, darinasmile commented on controllers/calendar.controler.ts
> +                    end: eventDateWithTime(order.date,order.time, order.hours),
Пробел

2021-03-25 09:26 UTC, darinasmile commented on client/src/containers/MasterCabinet/MasterCabinet.tsx
>          setTimeout(() => { dispatch(getMasterOrders(id)) }, 50); //todo !!!
Зачем нужен setTimeout?

2021-03-25 09:26 UTC, darinasmile commented on client/src/containers/Schedule/Schedule.tsx
> +    const closeShowMore = () => {
Лучше использовать useCallback

2021-03-25 09:26 UTC, darinasmile commented on client/src/containers/Schedule/Schedule.tsx
> +    const openShowMore = (event) => {
И тут тоже

2021-03-25 09:26 UTC, darinasmile commented on client/src/interfaces.ts
> +    photoURL: string
А почему photoUrl обязательный параметр?

2021-03-26 09:00 UTC, kostiantyn-chechel commented on controllers/calendar.controler.ts
> +                    end: eventDateWithTime(order.date,order.time, order.hours),
Добавил настройки в prettier

2021-03-26 09:00 UTC, kostiantyn-chechel commented on client/src/containers/Schedule/Schedule.tsx
> +    const closeShowMore = () => {
поменял

2021-03-26 09:00 UTC, kostiantyn-chechel commented on client/src/containers/Schedule/Schedule.tsx
> +    const openShowMore = (event) => {
поменял

2021-03-26 09:02 UTC, kostiantyn-chechel commented on client/src/interfaces.ts
> +    photoURL: string
поменял

2021-03-26 10:50 UTC, darinasmile approved these changes

2021-03-26 11:11 UTC, merged